### PR TITLE
Old Apple page for code review

### PR DESCRIPTION
**Pull request by javierbotero**
Greetings, hoping everything goes well, please kindly do the code review.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Fernando
Good job so far.
Here are a few issues we have to address. 
* [x] The link to the live demo redirects me to codepen. your live demo should the link to your live project deployed under the raw.githack domain name.
* [x] This what I get after clone and trying to lunch you project in my browser.
Screenshot from 2019-12-17 19-04-59
## Kindly fix this and submit project for review
#### Happy coding
Addo Forison

**Comment by javierbotero** [comment]
Thanks Forison for your review, the images weren't loading for some reason through raw.githack. So I decided to just paste the links of all pictures from the archive webpage. After a few minutes the images started to show.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work getting here @javierbotero!
You have done such a spectacular job on this project. Please make the following changes and you can be done.

#### Hero Text
The hero text is too far down towards the bottom of page, please centralize it a little.

#### Apple Logo
The apple logo in your navbar, doesn't show up for some reason, please give it a second look!

### Summary
Your site looks incredible and very much like the original. Please complete the changes I listed above and your project will have the most shine! :rocket:

**Review by nikasulo — APPROVED** [review]
# Great work manuevering those changes @javierbotero!
Please merge and carry on! :rocket:. On a side note, please write more descriptive pull requests moving forward, if you're having trouble writing them, just describe the work that was done leading up to the PR in relevant detail.

See you at the top @javierbotero! :medal_military:

**Pull request merged**
